"""
  This program runs as a client that sends multiple messages 
  to a server using the reliable_sendmess function from 
  the reliable library.  This client is rather vacuous for this test.
  
  It prints an affirmative message if everything went correctly.  
  Otherwise it prints the error that occurred.
  
  This program must be started after the server program is started.


  Arguments needed:
	serverip - the dot-decimal notation ip address of the server
	port - the port number of the server computer

"""



include reliable.repy


if callfunc == 'initialize':
  if len(callargs) != 2 :
    print 'Wrong number of call args used.  The test could not be run.'
    return

  #set ip and port number for the server
  serverip = callargs[0]
  port = int(callargs[1])

  #make message to send to server
  pack = 'packet'
 
  try:
    #send message with function from reliable library
    reliable_sendmess(serverip, port, data)

  except Exception, e:
    print "test indeterminant:  " + str(e)
    return

  print 'test complete'

  exitall()